[tool.poetry]
name = "app"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.115.2"
uvicorn = "^0.32.0"
<<<<<<< HEAD
=======
sqlalchemy = "^2.0.36"
>>>>>>> eff2002 ( On branch master)


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
